### PR TITLE
[Release] Milestone M190

### PR DESCRIPTION
**Pull request by derrickstolee**
Major Updates
----------------

* Comes with `microsoft/git` v2.32.0.vfs.0.4.
* This release will be available via `winget`.
* The `gvfs upgrade` verb is deprecated. Any future updates will be taken via `winget`.
* This version of Git has an upgrade mechanism that can advance independently of VFS for Git. Run `git update-microsoft-git` to update your Git version.
* The build system has been updated to use a more recent version of .NET.
* All macOS and POSIX code has been removed to simplify the build system.
* A FastFetch bug around deleting files has been fixed.
* A prefetch bug around downloading a small number of files has been fixed.

Special thanks to contributors @ldennington, @tyrielv, @50Wliu, and @SteveBenz.

Pull Requests
---------------

* #1738: Bumping version of update-winget action
* #1747: UpgradeVerb: write deprecation notice
* #1745: do not exit early if no blobs found for a period when prefetching
* #1740: Skip launching UI if running unattended
* #1737: Update Git to v2.32.0
* #1746: Delete custom upgrader
* #1741: Fix winget tag specification
* #1744: Overhaul build and project systems and drop Mac/POSIX code
* #1736: Update Git to v2.31.1.vfs.0.3
* #1735: Bumping winget action version
* #1734: Adding winget workflow
* #1733: Update Git to include 2.31.1
* #1730: Fix an issue with FastFetch when deleting files
* #1732: Use one NuGet feed
* #1726: Config: commitGraph.generationVersion=1

### CODE REVIEW

**Comment by derrickstolee** [comment]
A lot of the PR merge commits look like they have broken builds, but this is because I had forgotten to disable the CI trigger on the old Azure Pipelines builds.

**Review by mjcheetham — APPROVED** [review]

**Comment by 50Wliu** [comment]
@derrickstolee question - in the release notes you wrote "This release will be available via winget". Will the release also be published to GitHub, i.e. https://github.com/microsoft/VFSForGit/releases, or will it be available _only_ through winget?
(As an addendum, has this release been published yet? Strangely I don't have winget installed so I can't check, even though I'm running Insider builds.)

**Comment by derrickstolee** [comment]
Hi, @50Wliu. The release will also be available on the releases page. This release got cut short during our pipelines for generating the signed builds, and we might delay the full release until Git 2.33.0 is release in August. Thanks for your interest!

**Comment by 50Wliu** [comment]
Thanks!

**Pull request merged**
