### PR TITLE
Merge milestones/M158 to releases/shipped

### PR DESCRIPTION
**Pull request by jeschu1**
## Release notes

* Allows dehydration of specific folders.
* Fixes an issue on macOS where files with the executable mode bit set could fail to run if not hydrated before first run.
* Includes Git 2.23, with new verbs `switch` and `restore`.
* Various bug fixes and performance improvements.

### List of PRs included
#1518 [Merge to M158] Call multi-pack-index with --no-progress
#1513 Sparse UI cleanup
#1498: Don't allow Executables to be Placeholder
#1506 from Mac installer preinstall failure
#1323 Dehydrate folders
#1508: diff: use csharp driver for better function headers in .cs files
#1499 from pmj/mac-projfs-offline-io-registration-no-kext-user-version-validation
#1507 Check the disposing flag in Dispose methods
#1466 from Better installer logs
#1486: Clean up Register/Unregister for OfflineIO
#1485: Mark panic strings as 'public' so they appear in Console
#1482 from pmj/mac-projfs-1479-1480-no-follow-symlinks
#1487: Use the full path to GVFS.Hooks executable in the hook configuration
#1483 from pmj/mac-projfs-shadowed-variable-bugfixes
#1412 from github/case-sensitive-repos
#1452: Correct Upgrade Messages for Mac
#1476 Mark MoveIndexFileFails as MacOnly because CmdRunner on Windows failing
#1473 Mac: Add mdworker_shared to the IsFileSystemCrawler block list
#1469 from Enabling Service verb Functional tests
#1389: Update Git to v2.23.0
#1467 Add a global setup class when using a --test= option
#1445: Check for new Panic Logs where PrjFSKextLogDaemon is started
#1289 from Actionable notifications
#1440: Add LogInfo / LogWarning messages to PrjFSLib
#1456 from Auto-unmount repos in pre-install
#1411 from github/backing-root-fixes
#1429 from pmj/mac-kext-182-block-offline-empty-file-access
#1428 from github/move-index-test
#1448 from github/use-dir-sep-char
#1450 Add information for when lock is release by process not owning the lock
#1446 Cleanup virtualizer tests
#1449 Don't log errors when MaintenanceSteps fail due to the repo being deleted
#1436: [Mac kext] Allow privileged system service 'amfid' to hydrate
#1337: [Mac Kext] Remove '/System/Volumes/Data' when only in path
#1408: Include panic logs for vfs in diagnose
#1431 Add lock around writes to SQLite database tables
#1409 from Halterer/SubDirectoryInfoObject
#1417: Update mac uninstall script to remove GVFS service directory
#1425: update NUnit dependencies
#1416 Mac: Fix and enable remaining dehydrate functional tests
#1421: Update Git, drop MIDX writes
#1208 from pmj/mac-kext-182-no-writes-on-offline-roots
#1280 from pmj/mac-kext-resize-roots
#1415: Update Git to include octopus merge bugfix
#1363: Handle corrupt objects on Mac
#1351 No longer set PATH for git process and remove use of gvfs hooks root
#1392 Mac: Add version information to kext and PrjFS logging daemon
#1308: Updating README.md
#1384: [Mac] Don't allow cloning or mounting on case sensitive volumes
#1399 Add SetupFixture for teardown to get the test results at the end
#1398 Mac: Don't download file sizes as part of OnEnumerateDirectory
#1394 Increasing precision of timestamps being logged
#1388: Proper error message for 'git gui' on Mac
#1393: Setup.iss: use {sys} variable when calling sc.exe
#1303: GVFS Health Feature

### CODE REVIEW

**Comment by wilbaker** [comment]
@jrbriggs @derrickstolee @jeschu1 should we hold this release for https://github.com/microsoft/git/pull/186 (and #1455)?

**Comment by wilbaker** [comment]
@jeschu1 I noticed that the changes included in this release (e.g. #1513) are tagged as M159, but this branch is named M158.  Is this PR for the M159 release?

I'm wondering if I incorrectly tagged #1492 as M159 (I merged it into master after `milestones/M158` was created).

**Comment by jeschu1** [comment]
@wilbaker I tagged this as 158 since that's our current sprint.  I believe we were hoping for an out of band release to get the hydration fix out quicker.  @jrbriggs, let me know if I should re-push as 159.

**Comment by wilbaker** [comment]
> I tagged this as 158 since that's our current sprint. I believe we were hoping for an out of band release to get the hydration fix out quicker.

@jeschu1 @jrbriggs is this going to be a Mac-only release?

**Comment by jrbriggs** [comment]
@wilbaker @jeschu1 @alameenshah no the release should be both platforms.

**Comment by wilbaker** [comment]
> @wilbaker @jeschu1 @alameenshah no the release should be both platforms.

@jrbriggs ok thanks! 

Any objects to porting #1517 to this branch (it has a fix for the background MIDX jobs causing out of memory exceptions)?

> I tagged this as 158 since that's our current sprint.

@jeschu1 how should PRs be tagged that are included in this release (or alternatively, how should PRs be tagged that will be in the next release)?

**Comment by wilbaker** [comment]
> Any objects to porting #1517 to this branch (it has a fix for the background MIDX jobs causing out of memory exceptions)?

I went ahead and created #1518 to merge in the fix for this release.  @derrickstolee and @jeschu1  have signed off and I'll merge it in as soon as the tests complete.

**Comment by alameenshah** [comment]
[GitHub VFSForGit Large Repo Build](https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=10393184&view=results)

**Comment by derrickstolee** [comment]
Please update description with list of PRs included, and possibly with the list of PRs in microsoft/git that were included.

**Comment by jeschu1** [comment]
@wilbaker I believe @alameenshah is working on the perf number comparison

**Pull request merged**
