### PR TITLE
Merge milestones/M153 to releases/shipped

### PR DESCRIPTION
**Pull request by jrbriggs**
## Release notes
- Includes Git 2.22
- Moves placeholder database into SQLite for better performance.
- Fixes when libgit2 repos are acquired and disposed for better performance of checkout (where detected) and other operations that rely heavily on the read-object hook.
- Adds additional logging for folder and file placeholder creation.
- Other bug fixes for reliability

For more details, please see the [full change log](https://github.com/microsoft/VFSForGit/milestone/9?closed=1)

### CODE REVIEW

**Comment by wilbaker** [comment]
Doh! Sorry didn't mean to start the Mac Large Repo build

**Comment by nickgra** [comment]
@jrbriggs Do you want to take #1241 into this branch (I'll merge to master shortly or on Monday morning)? Normally I wouldn't want to sneak something into a release but I'd rather start getting data on folder hydration sooner rather than later.

/cc: @wilbaker

**Comment by jrbriggs** [comment]
@nickgra Yes, I'd like #1241 for this release if it's ready to go.

**Comment by derrickstolee** [comment]
@jrbriggs did you want Git 2.22.0? #1259

**Comment by nickgra** [comment]
@jrbriggs I ported the heartbeat changes, whenever this release goes to EA, we should make a note to validate that we're seeing the new data flow all the way into telemetry (and that we update any queries that may be interested in heartbeats accordingly).

**Pull request merged**
