### PR TITLE
[WIP] initial build of GVFS provider for Linux

### PR DESCRIPTION
**Pull request by chrisd8088**
Please **DO NOT MERGE** -- this is a WIP branch to debug issues getting the GVFS provider to build and run on Linux.

(Note to @jrbriggs et al: I'm opening this PR because I want to see if this passes the CI checks on Mac and Windows; there may well be additional things I need to tweak in the tooling before it does.  Thanks and apologies!)

This is largely a duplicate of the macOS build tooling and platform-specific code, with some changes to ensure we build successfully on Linux (e.g., testing for `'$(OS)' != 'Windows_NT'` is no longer sufficient to determine that the platform is OS X).

Note that for now the `BuildGVFSForLinux.sh` script exits early, without checking if a native libprojfs library is available, performing any installation or packaging, etc.

The `GVFS.sln` configuration changes should ensure that the `ProjFS.Linux.Managed` and `GVFS.Platform.Linux` subprojects are built on all platforms (and the Mac and Windows equivalents
are built on Linux), so as to allow the `GVFS.UnitTests` project to build on Linux, as it seems to do multi-platform unit testing.

However, we don't yet require the `GVFS.Mount.Linux` project to build on other platforms, and the `GVFS.FunctionalTests` project's configuration and dependencies will also need to be revisited
once the Linux code is actually functional.

/cc @kivikakk @wrighty

### CODE REVIEW

**Comment by chrisd8088** [comment]
Huh, OK -- well, that passed CI, somewhat to my surprise!

@jrbriggs, @wilbaker, et al -- would you be able to check that you can still load things in Visual Studio, run builds on Windows and Mac, etc., with these changes?  And if they look OK, merge them (or make suggestions as necessary)?

Thanks very much!
Chris.

**Comment by kivikakk** [comment]
I've opened a PR that stacks on top of this one at https://github.com/github/VFSForGit/pull/4 which extracts `GVFS.Platform.Posix` from the commonalities between Mac and Linux. Let me know what you think; it should make supporting the two similar platforms less of a maintenance burden.

**Comment by kivikakk** [comment]
This PR has been rebased (as of the reset in #818).

**Comment by kivikakk** [comment]
@jrbiggs I've refactored the Linux and Mac platforms into a common base in this PR; seeing as this may not get merged for some time, the drift in the Mac platform will make rebasing this painful, as most of the changes will need to get moved to the `Posix` platform.

Would you accept a PR to `master` that did the refactor without introducing the Linux platform? This would make the eventual PR to merge Linux into the mainline much less fraught.

**Comment by jrbriggs** [comment]
Hey @kivikakk sorry for the delay. I like the idea of just doing the `Posix` refactoring in this PR and deferring the Linux work. I'm going to start reviewing this today. The biggest concern I have after the initial look is the introduction of the Mono dependency that would now be shipped on the Mac. Can you tell me more about why we need this? Could we defer that introduction until we have done the rest of the platform refactoring, with the introduction of the Linux platform? I think that would help focus the goals of each PR. Thanks!

**Comment by kivikakk** [comment]
> Could we defer that introduction until we have done the rest of the platform refactoring, with the introduction of the Linux platform?

Happy to! I'll get a PR up for that soon.

**Comment by kivikakk** [comment]
:arrow_right: https://github.com/Microsoft/VFSForGit/pull/926

**Pull request closed without merging**
