### PR TITLE
Add build badge for CI - Full Functional Tests

### PR DESCRIPTION
**Pull request by kewillford**

### CODE REVIEW

**Comment by sanoursa** [comment]
In the preview, it appears that both badges just render as "build: succeeded", which looks redundant. Can we customize the text in the badge at all? If not, do we need both of them? The functional test result is a superset of the build result, so should we just have the one badge for the functional tests?

**Comment by kewillford** [comment]
@sanoursa Yeah I looked at [Git for Windows](https://github.com/git-for-windows/git) and saw that it had multiple, but the full functional tests build does do everything so only having that one makes sense.

**Comment by nickgra** [comment]
Do we want to set up badges for Mac Build/Functional Tests as well? Many open source projects that are cross-platform have separate badges for each platform.

See https://github.com/dotnet/roslyn for an example (although we probably don't want a matrix of badges that is so expansive)

**Comment by sanoursa** [comment]
@nickgra I like that idea, and the repo you link to provides a good pattern for labeling the badges as well. I think it would be nice to have a table of Windows/Mac vs Build/Tests.

**Pull request merged**
