### PR TITLE
Fix for #1743 - do not exit early if no blobs found for a period when prefetching.

### PR DESCRIPTION
**Pull request by tyrielv**
Fix for #1743 - do not exit early if no blobs found for a period when prefetching.

### CODE REVIEW

**Comment by derrickstolee** [comment]
@tyrielv: did you build and install this locally to verify that it fixes your larger scenario? I'm not seeing a clear reason why this fixes your case.

**Comment by tyrielv** [comment]
I'm still working on verifying it, but here's the reasoning:

If it takes more than ChunkSize * TimeoutMs (ie about 7 minutes) for the missingBlobs collection to produce its first value, then the loop currently exits and returns false. If it returns false, then the while loop on line 74 never runs and won't try again, even though the producer for missingBlobs is still running.

In my scenario it took about 1 hour for the missingBlobs producer to finish running and it only discovered 3 missing blobs out of  1.6 million, so it is very likely that there was at least one 7 minute gap before the 3 blobs were all discovered.

**Comment by derrickstolee** [comment]
> I'm still working on verifying it, but here's the reasoning:
> 
> If it takes more than ChunkSize * TimeoutMs (ie about 7 minutes) for the missingBlobs collection to produce its first value, then the loop currently exits and returns false. If it returns false, then the while loop on line 74 never runs and won't try again, even though the producer for missingBlobs is still running.

I see. I now can connect the dots that the early stage is _really slow_ in some cases.

> In my scenario it took about 1 hour for the missingBlobs producer to finish running and it only discovered 3 missing blobs out of 1.6 million, so it is very likely that there was at least one 7 minute gap before the 3 blobs were all discovered.

And I didn't expect this to be so slow, but I suppose it would be when checking 1.6 million blobs via libgit2. I'm more convinced that this is a fix, but I appreciate you doing the extra testing.

We won't want to merge this until after #1744 is merged, anyway.

**Comment by derrickstolee** [comment]
@tyrielv: #1744 is merged. Could you update your branch to kick off a new merge? That will allow us to run the PR validation builds. One easy way is to run `git commit --amend --no-edit && git push -f <remote> issue1743`

**Comment by tyrielv** [comment]
@derrickstolee can you approve the workflow so this can run tests?

**Review by derrickstolee — APPROVED** [review]

**Pull request merged**
