### PR TITLE
Deploy to winget via wingetcreate

### PR DESCRIPTION
**Pull request by ldennington**
Remove the custom mjcheetham/update-winget task in favor of the wingetcreate tool.

As with microsoft/git, this change should not be merged until the next release of `wingetcreate` - however, I wanted to get it queued up and allow a chance for review so that we'll be ready as soon as that release happens.

### CODE REVIEW

**Comment by derrickstolee** [comment]
The functional tests are currently broken and will be fixed with #1760.

**Comment by ldennington** [comment]
> The functional tests are currently broken and will be fixed with #1760.

Thanks for the heads up!

**Comment by derrickstolee** [comment]
@ldennington If you force-push your branch you'll get green builds, I expect.

**Comment by ldennington** [comment]
> @ldennington If you force-push your branch you'll get green builds, I expect.

Fingers crossed 😊 .

**Review by derrickstolee — APPROVED** [review]

**Pull request merged**
